### ISSUE TITLE
Allow deleting config/template/project parameters

### ISSUE THREAD

**Issue by stecydube** [QualiSystems/FluentTc#33]

**Comment by borismod** [comment]
I will work on it in the coming days.

**Comment by borismod** [comment]
Done in 0.0.0.115

You can use:
works for templates as well
                .DeleteBuildConfigurationParameter(_ => _.Id("buildConfigId"), __ => __.ParameterName("parameter.name"));

                .DeleteProjectParameter(_ => _.Id("projectId"), __ => __.ParameterName("parameter.name"));
