### ISSUE TITLE
Allow to attach a VCS root to a build configuration and also change checkout rules

### ISSUE THREAD

**Issue by stecydube** [QualiSystems/FluentTc#34]
From the TeamCity REST API documentation:

> Attach VCS root to a build configuration: POST http://teamcity:8111/httpAuth/app/rest/buildTypes/<buildTypeLocator>/vcs-root-entries. The XML/JSON posted is the same as retrieved by GET request to http://teamcity:8111/httpAuth/app/rest/buildTypes/<buildTypeLocator>/vcs-root-entries/<id> except for the secure settings like password: these are not included into responses and should be supplied before POSTing back.

See the full [TeamCity REST API documentation](https://confluence.jetbrains.com/display/TCD9/REST+API)

**Comment by alessandromuresan** [comment]
This is really important! Has anyone been working on this lately?

**Comment by alessandromuresan** [comment]
Yup, I'll send you a PR when I find some spare time :smiley:

**Comment by borismod** [comment]
I've added up-for-grabs label, hoping somebody would pick this issue from http://up-for-grabs.net/ web site :smile:

**Comment by GibbOne** [comment]
I just introduced some operations regarding VCS Root [here](https://github.com/GibbOne/FluentTc/tree/feature/GibbOne_Vcs_Operations):
- VCS Root creation
- VCS Root attachment (without checkout roles)

It works for me. But I need more time to create acceptance test and unit tests. 
In the meanwhile, feel free to suggest any improvements.

I will ask for a pull request soon.

**Comment by borismod** [comment]
@GibbOne any update on this?

**Comment by borismod** [comment]
Resolved thanks to @GibbOne 
Available in nuget package FluentTc 0.0.0.236
