### ISSUE TITLE
The encoding requested does not have a corresponding decoder

### ISSUE THREAD

**Issue by vilkelyte** [QualiSystems/FluentTc#40]
Hello, whenever I try to use any of your library methods I get this Easyhttp error :( , do you have any idea why?

The encoding requested does not have a corresponding decoder
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: JsonFx.Serialization.SerializationException: The encoding requested does not have a corresponding decoder:

Source Error:

Line 15:         public void GetLatestBuildForConfig(string configId)
Line 16:         {
Line 17:             var buildConfiguration =
Line 18:                 _remoteTc.Connect(_ => _.ToHost(_teamCitySettings).AsGuest())
Line 19:                     .GetBuilds(_ => _.BuildConfiguration(x => x.Id(configId)));

Stack Trace:

[SerializationException: The encoding requested does not have a corresponding decoder]
   EasyHttp.Codecs.DefaultDecoder.ObtainDeserializer(String contentType) in d:\BuildAgent-03\work\48c24454c251185c\src\EasyHttp\Codecs\DefaultDecoder.cs:43
   EasyHttp.Codecs.DefaultDecoder.DecodeToStatic(String input, String contentType) in d:\BuildAgent-03\work\48c24454c251185c\src\EasyHttp\Codecs\DefaultDecoder.cs:22
   EasyHttp.Http.HttpResponse.StaticBody(String overrideContentType) in d:\BuildAgent-03\work\48c24454c251185c\src\EasyHttp\Http\HttpResponse.cs:111
   FluentTc.Engine.TeamCityCaller.Get(String urlPart) +118
   FluentTc.Engine.TeamCityCaller.GetFormat(String urlPart, Object[] parts) +124
   FluentTc.Engine.BuildsRetriever.GetBuildWrapper(BuildHavingBuilder buildHavingBuilder, CountBuilder countBuilder, BuildIncludeBuilder buildIncludeBuilder) +247
   FluentTc.Engine.BuildsRetriever.GetBuilds(Action`1 having, Action`1 count, Action`1 include) +186
   FluentTc.ConnectedTc.GetBuilds(Action`1 having) +255
   MyBachelor.Services.TeamCityDataService.GetLatestBuildForConfig(String configId)

**Comment by borismod** [comment]
Hello @vilkelyte 

Sorry for the delayed response. I am just back from vacation and trying to catch up with emails.

I suspect that the issue is with EasyHttp library. Make sure you use version 1.6.67.0

Let me know if it helped

**Comment by borismod** [comment]
EasyHttp was fixed and FluentTc uses now 1.6.85 version of EasyHttp
