### ISSUE TITLE
wrong nuget package dependency

### ISSUE THREAD

**Issue by sokolovsv90** [QualiSystems/FluentTc#43]
As of 4/4/2016, project depends on EasyHttp 1.6.85, but nuget package states that project is dependent on EasyHttp 1.6.67.0, which leads to System.TypeLoadException bugginess

**Comment by borismod** [comment]
@sokolovsv90 I am on it

**Comment by sokolovsv90** [comment]
would be nice to update that in nuget gallery aswell, because `Install-Package FluentTc` still pulls old dependency

**Comment by borismod** [comment]
Fixed in FluentTc 0.0.0.154 
@sokolovsv90, Can you verify please?

**Comment by sokolovsv90** [comment]
sweet, thanks!
