### ISSUE TITLE
Need ability to get buildId on post buildQueue

### ISSUE THREAD

**Issue by nex-54** [QualiSystems/FluentTc#71]
I want to have ability to get Build.Id and other info about build from "/app/rest/buildQueue" request

**Comment by borismod** [comment]
@nex-54 isn't it covered by GetBuildQueue method :grey_question: 

https://github.com/QualiSystems/FluentTc/wiki/RemoteTc#build-queue-operations

**Comment by nex-54** [comment]
@borismod No, i need ability to get exactly my queue. Without Build.Id i can't know witch queue is mine. One BuildConfiguration may be run multiple from different sources at one time.
I have commit to fix it. I will do pull request when check all tests.

**Comment by borismod** [comment]
@nex-54 sure, thanks. I'll be glad to see what you mean
