### ISSUE TITLE
Question about getting running builds

### ISSUE THREAD

**Issue by epiespen** [QualiSystems/FluentTc#82]
### Running builds
First of all, great work, love FluentTc!

I have created a monitor screen displaying status of latest build of all buildTypes of a Project. Green for success and red for failure. Now I want to add yellow for currently running builds, but I can't figure out how to get that info. 

So the question is basically how do I acecss data about any currently running builds and their states?

**Comment by borismod** [comment]
@epiespen I am glad you like it. Do you mean get list of running builds?

Just getting the basic list of running builds is like this:
```C#
            var runningBuilds = new RemoteTc().Connect(a => a.ToHost("tc").AsGuest())
                .GetBuilds(which => which.Running()));
```
with some additional data:
```C#
            var runningBuilds = new RemoteTc().Connect(a => a.ToHost("tc").AsGuest())
                .GetBuilds(which => which.Running(), 
                    include => include.IncludeDefaults().IncludeStartDate());

```

Please note that there is no status on the running builds, only on finished. Also please note that when a build is "getting source code" it's not considered by TeamCity as running.

**Comment by borismod** [comment]
with additional data and paging:
```C#
            var runningBuilds = new RemoteTc().Connect(a => a.ToHost("tc").AsGuest())
                .GetBuilds(which => which.Running(), 
                    include => include.IncludeDefaults().IncludeStartDate(), 
                    paging => paging.Start(50).Count(10));

```

**Comment by epiespen** [comment]
That did the trick! Thanks so much! :) Keep up the good work!

**Comment by borismod** [comment]
@epiespen I am excited to see your monitor. I am sure it might be useful for many others. Are you going to publish it on github?

**Comment by epiespen** [comment]
I'll keep it as a private repo until I've got a couple of more things in place :) When I'm happy with the basic features I'll publish it and let you know as well as link to FluentTc in the readme. Thanks again!
