### ISSUE TITLE
Start build with parameters and options

### ISSUE THREAD

**Issue by evolvedlight** [QualiSystems/FluentTc#83]
### Bug/Feature Request
I would like to start a build with custom parameters at the top of the build queue. I can do either or these, not both.

Happy to create a PR if you think this is valuable

### Test to reproduce
```C#
_Please provide necessary steps for reproduction of this issue_.
[Test]
public void Test_To_Reproduce_The_Issue()
{
   client.RunBuildConfiguration(_ => _.Id(someBuildConfig.Id),
                    _ => _.Parameter("testParam1", testParam1Value).Parameter("testParam2", testParam2Value), _ => _.QueueAtTop());
}
```

### Affected versions

Product | Version
--------|--------
FluentTc |  latest
TeamCity | any
Autofac |
EasyHttp |
SharpZipLib |
System.IO.Abstractions | 
TeamCity.ServiceMessages |

**Comment by borismod** [comment]
@evolvedlight I'm glad you're using FluentTc. It would be great if you could submit a PR.
