### ISSUE TITLE
Artifact dependencies are missing information on the referenced build configuration

### ISSUE THREAD

**Issue by 3breadt** [QualiSystems/FluentTc#92]
The ArtifactDependency object currently does not contain information about the build configuration from which artifacts are referenced. An artifact dependency's ID property does _not_ identify the referenced build config as it does with the snapshot dependency object.

The "source-buildType" element of the REST response needs to be parsed and provided in the ArtifactDependency object, so that the information is available.

This issue is addressed by pull request #91

**Comment by 3breadt** [comment]
Pull request has been merged. Issue resolved.

**Comment by borismod** [comment]
@3breadt thanks for your contribution. You were added to the list of contributors: https://github.com/QualiSystems/FluentTc/blob/master/CONTRIBUTORS.md
